### ISSUE TITLE
在库中配置下载清单

### ISSUE THREAD

**Issue by Reginer** [azhon/AppUpdate#75]
provider信息可以直接在库中配置，不需要手动加到项目里。把手动加到项目中的内容写到库里就可以了。
Provider换个名字

**Comment by azhon** [comment]
库中自定义FileProvider？这样会有冲突吗？

**Comment by Reginer** [comment]
不会有冲突的。但是必须要自己创建个Provider继承FileProvider。比如像下面这样:
```
<provider
            android:name=".UpdateFileProvider"
            android:authorities="${applicationId}.update.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/update_file_path"/>
        </provider>
```
```
public class UpdateFileProvider extends FileProvider {
}
```

**Comment by azhon** [comment]
好的，感谢！下个版本我更改下。

**Comment by ZQ173** [comment]
> 好的，感谢！下个版本我更改下。

老铁 你改完以后我项目安装不了了，我有两三个项目都是用你的，结果更新到 2.8.0 后全炸了，报错如下：

The application could not be installed: INSTALL_FAILED_CONFLICTING_PROVIDER
Installation failed due to: 'null'

**Comment by azhon** [comment]
怎么在issue上没看到你的问题？你检查下app的gradle有没有配置



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZQ173"<notifications@github.com&gt;; 
发送时间: 2020年3月2日(星期一) 晚上8:28
收件人: "azhon/AppUpdate"<AppUpdate@noreply.github.com&gt;; 
抄送: "阿钟"<958460248@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [azhon/AppUpdate] 在库中配置下载清单 (#75)



 
好的，感谢！下个版本我更改下。
  
老铁 你改完以后我项目安装不了了，我有两三个项目都是用你的，结果更新到 2.8.0 后全炸了，报错如下：
 
The application could not be installed: INSTALL_FAILED_CONFLICTING_PROVIDER
 Installation failed due to: 'null'

**Comment by ZQ173** [comment]
issue 发完就看到 app 的 gradle 那边没配置，配置好了就可以了，多谢哈！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Code Porter"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月2日(星期一) 晚上10:04
收件人:&nbsp;"azhon/AppUpdate"<AppUpdate@noreply.github.com&gt;;
抄送:&nbsp;"ZQ"<173123831@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [azhon/AppUpdate] 在库中配置下载清单 (#75)



怎么在issue上没看到你的问题？你检查下app的gradle有没有配置 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "ZQ173"<notifications@github.com&amp;gt;;  
 发送时间: 2020年3月2日(星期一) 晚上8:28 
 收件人: "azhon/AppUpdate"<AppUpdate@noreply.github.com&amp;gt;;  
 抄送: "阿钟"<958460248@qq.com&amp;gt;; "State change"<state_change@noreply.github.com&amp;gt;;  
 主题: Re: [azhon/AppUpdate] 在库中配置下载清单 (#75) 
 
 
 
   
 好的，感谢！下个版本我更改下。 
    
 老铁 你改完以后我项目安装不了了，我有两三个项目都是用你的，结果更新到 2.8.0 后全炸了，报错如下： 
   
 The application could not be installed: INSTALL_FAILED_CONFLICTING_PROVIDER 
  Installation failed due to: 'null'

**Comment by Reginer** [comment]
实际上不需要配置gradle的，主要是下面代码起的作用。
```
android:authorities="${applicationId}.update.provider"
```
把之前这个库在清单文件里响应的注册信息删除掉

**Comment by ZQ173** [comment]
> 实际上不需要配置gradle的，主要是下面代码起的作用。
> 
> ```
> android:authorities="${applicationId}.update.provider"
> ```
> 
> 把之前这个库在清单文件里响应的注册信息删除掉

一开始清单里的配置我都删掉咯，也 clean、rebuild 了

**Comment by Reginer** [comment]
@ZQ173 
是的，这需要库的开发者来做修改，将android:authorities指定为可变

**Comment by ZQ173** [comment]
> @ZQ173
> 是的，这需要库的开发者来做修改，将android:authorities指定为可变

对 这样库的使用者就不用配置 gradle 了，一开始我也以为库都配置好了的。

**Comment by Reginer** [comment]
> > @ZQ173
> > 是的，这需要库的开发者来做修改，将android:authorities指定为可变
> 
> 对 这样库的使用者就不用配置 gradle 了，一开始我也以为库都配置好了的。

[这个文件11行修改为:](https://github.com/azhon/AppUpdate/blob/master/appupdateX/src/main/AndroidManifest.xml)

```
android:authorities="${applicationId}.fileProvider"
```
就可以了

**Comment by azhon** [comment]
两位大哥进下群，来聊下你们想干啥?没看懂你们的聊天

**Comment by ithomasoft** [comment]
+1

**Comment by azhon** [comment]
下个版本继续优化这里，将在gradle配置这一步省去
